/*
 * This Java source file was generated by the Gradle 'init' task.
 * Demo to class on adding code
 * Comment on main branch
 */
package cs3354_hello_world;
public class App {
    public String getStarted() {
        return "Getting Started!";
    }

    public static void main(String[] args) {
        int mathresult = 0;
        System.out.println(new App().getStarted());

        Hello HelloInstance = new Hello();
        System.out.println(HelloInstance.sayHello());
        DoMath mathwhiz = new DoMath();
        mathresult = mathwhiz.increment(1);
        System.out.println("Increment result: " + mathresult);
        mathresult = mathwhiz.decrement(mathresult);
        System.out.println("Decrement result: " + mathresult);

        // Reflection Examples
        mathwhiz.printClassAndPackageName();
        HelloInstance.printClassAndPackageName();
        HelloInstance.printFields();
        HelloInstance.printMethods();
        // End Reflection Examples
 
        // Nested Class Examples
        // No instantiation needed for accessing StaticInnerClass's static methods
        // Instantiation needed for accessing StaticInnerClass's instance methods. 
        OuterNestedClass.StaticInnerClass.printStaticStaticMessage();
        OuterNestedClass.StaticInnerClass staticNested = new OuterNestedClass.StaticInnerClass();
        staticNested.printStaticInstanceMessage();

        // Instantiation needed for accessing methods of nested NonStaticInnerClass
        OuterNestedClass outerObject = new OuterNestedClass();
        OuterNestedClass.NonStaticInnerClass inner = outerObject.new NonStaticInnerClass();
        inner.printNonStaticInnerClassMessage();
        // End Nested Class Examples

        Goodbye thankyou = new Goodbye();
        System.out.println(thankyou.sayGoodbye());
    }
}
